
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class BillOfQuantity
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BillOfQuantity()
    {

        this.Treatments = new HashSet<Treatment>();

    }


    public System.Guid BillOfQuantityID { get; set; }

    public string BillOfQuantityName { get; set; }

    public string BillOfQuantityDescription { get; set; }

    public Nullable<System.Guid> LabourID { get; set; }

    public Nullable<System.Guid> MaterialsID { get; set; }



    public virtual Labour Labour { get; set; }

    public virtual Material Material { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Treatment> Treatments { get; set; }

}

}
