
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class Building
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Building()
    {

        this.Departments = new HashSet<Department>();

        this.Floors = new HashSet<Floor>();

    }


    public System.Guid BLDID { get; set; }

    public string BuildingID { get; set; }

    public string Building_Description { get; set; }

    public string Campus { get; set; }

    public Nullable<System.Guid> CPSID { get; set; }

    public string BuildingCategory { get; set; }



    public virtual Campu Campu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Department> Departments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Floor> Floors { get; set; }

}

}
