
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class ComponentFinance
{

    public System.Guid ComponentFinanceID { get; set; }

    public string Dimension { get; set; }

    public Nullable<decimal> Quantity { get; set; }

    public Nullable<decimal> UnitRate { get; set; }

    public Nullable<decimal> ReplacementCost { get; set; }

    public Nullable<System.Guid> ComponentID { get; set; }



    public virtual Component Component { get; set; }

}

}
