
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class ComponentAttibute
{

    public System.Guid ComponentAttibuteID { get; set; }

    public string ComponentAttibuteName { get; set; }

    public string ComponentAttibuteDescription { get; set; }

    public Nullable<System.Guid> ComponentID { get; set; }



    public virtual Component Component { get; set; }

}

}
