
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class ComponentInspection
{

    public System.Guid ComponentInspectionsID { get; set; }

    public string ComponentInspectionsName { get; set; }

    public string ComponentInspectionNotes { get; set; }

    public Nullable<System.DateTime> InspectionCreationDate { get; set; }

    public Nullable<System.DateTime> InspectionCloseDate { get; set; }

    public Nullable<System.Guid> TreatmentsID { get; set; }

    public Nullable<System.Guid> ComponentID { get; set; }

    public Nullable<System.Guid> StaffID { get; set; }

    public System.Guid InspectionPriorityID { get; set; }

    public Nullable<System.Guid> InspectionStatusID { get; set; }

    public Nullable<System.Guid> WorkOrdersID { get; set; }



    public virtual Component Component { get; set; }

    public virtual LookupInspectionPriority LookupInspectionPriority { get; set; }

    public virtual LookupInspectionStatu LookupInspectionStatu { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual Treatment Treatment { get; set; }

    public virtual WorkOrder WorkOrder { get; set; }

}

}
