
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class Department
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {

        this.Staffs = new HashSet<Staff>();

    }


    public System.Guid DepartmentsID { get; set; }

    public string DepartmentsName { get; set; }

    public string DepartmentsDescription { get; set; }

    public Nullable<System.Guid> OrganisationID { get; set; }

    public Nullable<System.Guid> BuildingID { get; set; }



    public virtual Building Building { get; set; }

    public virtual Organisation Organisation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Staff> Staffs { get; set; }

}

}
