
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class Floor
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Floor()
    {

        this.Rooms = new HashSet<Room>();

    }


    public System.Guid FLID { get; set; }

    public string Floor1 { get; set; }

    public string Floor_Description { get; set; }

    public string BuildingID { get; set; }

    public string Campus { get; set; }

    public Nullable<System.Guid> BLDID { get; set; }



    public virtual Building Building { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Room> Rooms { get; set; }

}

}
