
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class Hierarchy
{

    public System.Guid HierarchyID { get; set; }

    public Nullable<int> HierachyScore { get; set; }

    public string HierarchyName { get; set; }

    public Nullable<System.Guid> HierarchyTypeID { get; set; }



    public virtual SetupHierarchy SetupHierarchy { get; set; }

}

}
