
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class Location
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Location()
    {

        this.Assets = new HashSet<Asset>();

    }


    public System.Guid LocationID { get; set; }

    public string Room { get; set; }

    public string Floor { get; set; }

    public string Building { get; set; }

    public string Address { get; set; }

    public string Suburb { get; set; }

    public string City { get; set; }

    public string LocationDescription { get; set; }

    public Nullable<System.Guid> OrganisationID { get; set; }

    public string Campus { get; set; }

    public Nullable<System.Guid> RoomID { get; set; }

    public Nullable<System.Guid> FloorID { get; set; }

    public Nullable<System.Guid> BuildingID { get; set; }

    public Nullable<System.Guid> CampusID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Asset> Assets { get; set; }

    public virtual Organisation Organisation { get; set; }

}

}
