
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class LookupLifecycleName
{

    public System.Guid LifecycleNameID { get; set; }

    public Nullable<int> LCN_ID { get; set; }

    public string LC_DESC { get; set; }

    public Nullable<int> OptimisticLockField { get; set; }

}

}
