
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class PerformanceMeasure
{

    public System.Guid PerformanceMeasureID { get; set; }

    public string AppearanceScore { get; set; }

    public Nullable<decimal> ConditionScore { get; set; }

    public Nullable<System.Guid> ComponentID { get; set; }

    public string LifecycleCurve { get; set; }

    public Nullable<System.DateTime> DateInspected { get; set; }

    public Nullable<System.DateTime> DateConditionChange { get; set; }

    public string DataAccuracy { get; set; }



    public virtual Component Component { get; set; }

}

}
