
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    
public partial class SpFilterInspection_Result1
{

    public System.Guid ComponentInspectionsID { get; set; }

    public string ComponentInspectionsName { get; set; }

    public string ComponentInspectionNotes { get; set; }

}

}
