
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    
public partial class spGetLocation_Result1
{

    public System.Guid LocationID { get; set; }

    public string Campus { get; set; }

    public string Building { get; set; }

    public string Floor { get; set; }

    public string Room { get; set; }

}

}
