
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    
public partial class spGetTreamtneInfo_Result2
{

    public System.Guid TreatmentsID { get; set; }

    public string TreatmentsName { get; set; }

    public string TreatmentsDescription { get; set; }

    public string BillOfQuantityName { get; set; }

    public string TreatType { get; set; }

    public string TreatTypeDescription { get; set; }

    public Nullable<decimal> TotalUnitRate { get; set; }

}

}
