
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class Staff
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Staff()
    {

        this.ComponentInspections = new HashSet<ComponentInspection>();

    }


    public System.Guid StaffID { get; set; }

    public string StaffName { get; set; }

    public string StaffDescription { get; set; }

    public Nullable<System.Guid> DepartmentsID { get; set; }

    public Nullable<System.Guid> RolesID { get; set; }

    public string ContactNumber { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ComponentInspection> ComponentInspections { get; set; }

    public virtual Department Department { get; set; }

    public virtual Role Role { get; set; }

}

}
