
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class Treatment
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Treatment()
    {

        this.ComponentInspections = new HashSet<ComponentInspection>();

    }


    public System.Guid TreatmentsID { get; set; }

    public string TreatmentsName { get; set; }

    public string TreatmentsDescription { get; set; }

    public Nullable<System.Guid> SuppliersID { get; set; }

    public Nullable<System.Guid> BillOfQuantityID { get; set; }

    public Nullable<decimal> TotalUnitRate { get; set; }

    public Nullable<System.Guid> TreatTypeID { get; set; }



    public virtual BillOfQuantity BillOfQuantity { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ComponentInspection> ComponentInspections { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual LookupTreatType LookupTreatType { get; set; }

}

}
