
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class V_4CAST_IMPORT
{

    public string OrganisationName { get; set; }

    public string Component_Title { get; set; }

    public string Campus { get; set; }

    public string Building { get; set; }

    public string BuildingCategory { get; set; }

    public string Floor { get; set; }

    public string Room { get; set; }

    public string Room_Description { get; set; }

    public string Room_Type { get; set; }

    public string AssetName { get; set; }

    public string ComponentName { get; set; }

    public string Material { get; set; }

    public string Utilisation { get; set; }

    public string EnvironmentalExposure { get; set; }

    public Nullable<decimal> ConditionScore { get; set; }

    public string AppearanceScore { get; set; }

    public Nullable<decimal> Quantity { get; set; }

    public string Dimension { get; set; }

    public Nullable<decimal> UnitRate { get; set; }

    public string ComponentCategory { get; set; }

    public string ComponentCoF { get; set; }

    public string LifecycleCurve { get; set; }

    public System.Guid LocationID { get; set; }

    public System.Guid OrganisationID { get; set; }

    public Nullable<System.Guid> CPSID { get; set; }

    public Nullable<System.Guid> BLDID { get; set; }

    public Nullable<System.Guid> FLID { get; set; }

    public Nullable<System.Guid> RMID { get; set; }

    public System.Guid AssetID { get; set; }

    public System.Guid ComponentID { get; set; }

    public System.Guid PerformanceMeasureID { get; set; }

    public System.Guid ComponentFinanceID { get; set; }

    public Nullable<System.DateTime> DateConditionChange { get; set; }

}

}
