
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class V_COMPONENT_FINANCE
{

    public string OrganisationName { get; set; }

    public string Campus { get; set; }

    public string Building { get; set; }

    public string BuildingCategory { get; set; }

    public string Floor { get; set; }

    public string Room { get; set; }

    public string Room_Description { get; set; }

    public string Room_Type { get; set; }

    public string AssetName { get; set; }

    public string ComponentName { get; set; }

    public string Material { get; set; }

    public Nullable<decimal> ConditionScore { get; set; }

    public Nullable<decimal> Quantity { get; set; }

    public string Dimension { get; set; }

    public Nullable<decimal> UnitRate { get; set; }

    public Nullable<System.DateTime> RateEffectiveDate { get; set; }

    public Nullable<System.DateTime> InstallationDate { get; set; }

    public Nullable<System.DateTime> DisposalDate { get; set; }

    public Nullable<double> ModerateUL { get; set; }

    public Nullable<double> RemainingLife_SOY { get; set; }

    public Nullable<double> RemainingLife_EOY { get; set; }

    public Nullable<double> EstInstallYear { get; set; }

    public Nullable<double> AcummulatedDepreciationPercent { get; set; }

    public Nullable<decimal> RepCost { get; set; }

    public Nullable<decimal> AcummulatedDepreciationCost { get; set; }

    public Nullable<double> AnnualDepreciationAmount { get; set; }

    public Nullable<decimal> WDV_SOY { get; set; }

    public Nullable<double> WDV_EOY { get; set; }

    public Nullable<decimal> NET_CHANGE_NEW_RATES { get; set; }

    public Nullable<System.DateTime> DateConditionChange { get; set; }

    public Nullable<decimal> Remaining_Health_Survey { get; set; }

    public Nullable<double> COND_BASED_ADJUSTMENT { get; set; }

    public string Component_Title { get; set; }

}

}
