
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IN4MDatabase
{

using System;
    using System.Collections.Generic;
    
public partial class WorkOrder
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public WorkOrder()
    {

        this.ComponentInspections = new HashSet<ComponentInspection>();

    }


    public System.Guid WorkOrdersID { get; set; }

    public string WorkOrderName { get; set; }

    public string WorkOrderDescription { get; set; }

    public Nullable<System.Guid> WorkOrderStatusID { get; set; }

    public Nullable<System.DateTime> CommencementDate { get; set; }

    public Nullable<System.DateTime> CompletionDate { get; set; }

    public Nullable<decimal> WorkOrderEstCost { get; set; }

    public Nullable<decimal> WorkOrderActualCost { get; set; }

    public Nullable<int> DecantingPercent { get; set; }

    public Nullable<decimal> TotalWorkOrderEstCost { get; set; }

    public Nullable<System.Guid> WorkOrderPriorityID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ComponentInspection> ComponentInspections { get; set; }

    public virtual LookupWorkOrderPriority LookupWorkOrderPriority { get; set; }

    public virtual LookupWorkOrderStatu LookupWorkOrderStatu { get; set; }

}

}
